---

ansible_user: root
ansible_ssh_pass: password
tools_directory: "/root/CloudianTools"
network_scripts_dir: "/etc/sysconfig/network-scripts"
hyperstore_installer_node: "{{ ansible_play_hosts | intersect(groups['installer-node']) | first }}"
hostname_nonfqdn: "{{ inventory_hostname.split('.')[0] }}"
bmc_cidr: "169.254.0.1{{ bmc_prefix }}"
bmc_netmask: "{{ bmc_cidr | ipaddr('netmask') }}"
