---

# TODO:
# - support manual mapping of MAC/addr->Nodename
# - support multiple DCs
# - support running without installer node
# - support adding all packages within a directory based on major OS version

- hosts: installer-node
  vars:
    hyperstore_version: "7.0"
    staging_directory: "/root/CloudianPackages"
  roles:
    - pre-installer

- hosts: cloudian
  vars:
    # by default the last octet of the existing/temp. DHCP address on a node is used
    net_frontend_net: "10.10.10"
    net_frontend_prefix: "/24"
    net_frontend_vlan: "10"
    net_backend_net: "10.20.20"
    net_backend_prefix: "/24"
    net_backend_vlan: "20"
    net_gateway: "10.10.10.1"
    net_dns1: "10.10.10.1"
    net_dns2: "10.10.10.1"
    net_bonding_opts: "mode=4 miimon=100"
    net_bonding_slave1: "eth1"
    net_bonding_slave2: "eth2"
    tools_directory: "/root/CloudianTools"
    hyperstore_installer_node: "{{ ansible_play_hosts | intersect(groups['installer-node']) | first }}"
    cfg_ipmi: False
    bmc_net: "10.20.20"
    bmc_prefix: "/24"
    bmc_gateway: "10.20.20.1"
  roles:
    - common
    - bmc

- hosts: installer-node
  vars:
    hyperstore_region: "region-1"
    hyperstore_datacenter: "DC1"
    hyperstore_rack: "RAC1"
    staging_directory: "/root/CloudianPackages"
  roles:
    - installer-node
