---

# Cloudian main
# see group_vars/* for Region and DC specific configuration
# see inventory for node level configuration
# all configuration parameters can be overridden in Region or DC
# order of precedence: cloudian < region < DC

- hosts: installer-node
  vars:
    hyperstore_version: "7.0.2.1"
    staging_directory: "/root/CloudianPackages/{{ hyperstore_version }}"
  roles:
    - pre-installer

- hosts: cloudian
  vars:
    net_bonding_opts: "mode=4 miimon=100"
    net_bonding_slave1: "ens255f0"
    net_bonding_slave2: "ens255f1"
    net_verify_nic: true
    net_cfg_routes: false
    bmc_cfg_ipmi: false
  roles:
    - common
    - bmc
