---

# TODO:
# - discovery of nodes based on NIC led blinking
# - static address mapping eg. nodes.ini
# - running without installer node (eg. separate runs within each DC)
# - adding all packages within a directory based on major OS version

- hosts: installer-node
  vars:
    hyperstore_version: "7.0"
  roles:
    - pre-installer

- hosts: cloudian
  vars:
    # by default the last octet of the existing/temp. DHCP address on a node is used
    # addresses can be overruled by specifying an INI file here:
    nodes_ini: "nodes.ini"
    net_frontend_net: "10.10.10"
    net_frontend_prefix: "/24"
    net_frontend_vlan: "10"
    net_backend_net: "10.20.20"
    net_backend_prefix: "/24"
    net_backend_vlan: "20"
    net_gateway: "10.254.254.1"
    net_dns1: "10.254.254.1"
    net_dns2: "10.254.254.1"
    net_bonding_opts: "mode=4 miimon=100"
    net_bonding_slave1: "eth1"
    net_bonding_slave2: "eth2"
    cfg_ipmi: False
    bmc_net: "10.30.30"
    bmc_prefix: "/24"
    bmc_gateway: "10.30.30.1"
    sys_timezone: "Europe/Amsterdam"
  roles:
    - common
    - bmc

- hosts: installer-node
  vars:
    hyperstore_region: "region-1"
    hyperstore_datacenter: "DC1"
    hyperstore_rack: "RAC1"
  roles:
    - installer-node
