---

- hosts: installer-node
  vars:
    hyperstore_version: "6.2.2"
    staging_directory: "/root/CloudianPackages"
  roles:
    - pre-installer

- hosts: cloudian
  vars:
    # by default the last octet of the existing/temp. DHCP address on a node is used
    # TODO: Add more logic here
    dc1_frontend_net: "10.10.10"
    dc1_frontend_prefix: "/24"
    dc1_frontend_vlan: "10"
    dc1_backend_net: "10.20.20"
    dc1_backend_prefix: "/24"
    dc1_backend_vlan: "20"
    dc1_gateway: "10.10.10.1"
    dc1_dns1: "10.10.10.1"
    dc1_dns2: "10.10.10.1"
    dc1_bonding_opts: "mode=4 miimon=100"
    dc1_bonding_slave1: "eth1"
    dc1_bonding_slave2: "eth2"
    tools_directory: "/root/CloudianTools"
    hyperstore_installer_node: "{{ ansible_play_hosts | intersect(groups['installer-node']) | first }}"
  roles:
    - common

- hosts: installer-node
  vars:
    hyperstore_region: "region-1"
    hyperstore_datacenter: "DC1"
    hyperstore_rack: "RAC1"
    staging_directory: "/root/CloudianPackages"
  roles:
    - installer-node
