---

# NOTE: the installer .bin is expected to be present under ../files
- name: Copy Cloudian HyperStore installer
  copy:
    src: "{{ role_path }}/files/CloudianHyperStore-{{ hyperstore_version }}.bin"
    local_follow: true  # just in case the local file is a symlink
    dest: "{{ staging_directory }}"
    mode: 0755
  when: not run_from_iso|bool

# NOTE: the license is expected to be present under ../files
- name: Copy Cloudian license
  copy:
    src: "{{ role_path }}/files/cloudian_license.lic"
    dest: "{{ staging_directory }}"
    local_follow: true  # just in case the local file is a symlink
  when: not run_from_iso|bool

- name: Extract Installer .bin
  shell: "cd {{ staging_directory }} && ./CloudianHyperStore-{{ hyperstore_version }}.bin cloudian_license.lic"
  args:
    chdir: "{{ staging_directory }}"
    executable: /bin/bash
    creates: "{{ staging_directory }}/RELEASENOTES"
  when: not run_from_iso|bool

- name: Copy CIC preseed File
  copy:
    src:  "{{ project }}/preseed.conf"
    dest: "{{ staging_directory }}/preseed.conf"
