---

- name: Generate cloudian-installation-key SSH key
  shell: ssh-keygen -b 2048 -t rsa -f {{ staging_directory }}/cloudian-installation-key -q -N ''
  args:
    creates: "{{ staging_directory }}/cloudian-installation-key"
  when: not run_from_iso|bool and not run_from_orch|bool

# reads the new pub key from the installer node into a variable...
- name: Slurp cloudian-installation-key
  slurp: src="{{ staging_directory }}/cloudian-installation-key.pub"
  register: cloudian_installation_key
  when: not run_from_iso|bool and not run_from_orch|bool

# .. and set it as fact because registered variables are only valid on the host
# for the rest of the current playbook run
- name: Set pub key as fact
  set_fact:
    cloudian_installation_key: "{{ cloudian_installation_key }}"
    cacheable: true
  when: not run_from_iso|bool and not run_from_orch|bool

# the ISO carries a pre generated key because every ansible run is independent
# (it occurs locally on each node)
# orch mode also generates an 'external' key pair
- name: Copy Cloudian Installer SSH priv key
  copy:
    src: "{{ project }}/cloudian-installation-key"
    dest: "{{ staging_directory }}/cloudian-installation-key"
    mode: 0600
  when: run_from_iso|bool or run_from_orch|bool

- name: Copy Cloudian Installer SSH pub key
  copy:
    src: "{{ project }}/cloudian-installation-key.pub"
    dest: "{{ staging_directory }}/cloudian-installation-key.pub"
    mode: 0644
  when: run_from_iso|bool or run_from_orch|bool
