---

- name: Slurp System_Setup
  slurp: src="{{ staging_directory }}/system_setup.sh"
  register: system_setup
  when: not run_from_iso

- set_fact:
    cloudian_system_setup: "{{ system_setup }}"
    cacheable: true
  when: not run_from_iso
