---

- name: Deploy Cloudian Installer SSH key
  authorized_key:
    user: root
    state: present
    key: "{{  hostvars[hyperstore_installer_node]['cloudian_installation_key']['content'] | b64decode }}"
