---

- name: Deploy Cloudian Installer SSH key
  authorized_key:
    user: root
    state: present
    key: "{{ hostvars[groups['installer-node'][0]]['cloudian_installation_key']['content'] | b64decode }}"
  when: not run_from_iso
