---

- name: Configure Cloudian Data Disks
  #shell: "yes '' | TERM=xterm {{ tools_directory }}/system_setup.sh --configure-disks `lsblk  --output NAME --nodeps --noheadings | paste -d' ' -s`"
  shell: echo
  args:
    creates: "{{ tools_directory }}/fslist.txt"

- debug:
    msg: "Placeholder. Disk formatting broken atm"
