---

- name: Write out System_Setup
  copy:
    dest: "{{ tools_directory }}/system_setup.sh"
    # see roles/pre-installer/tasks/distr_systemsetup.yml
    content: "{{ hostvars[groups['installer-node'][0]]['cloudian_system_setup']['content'] | b64decode }}"
    owner: root
    mode: 0750
  when: not run_from_iso|bool

- name: Copy system_setup.sh
  copy:
    src: "{{ role_path }}/files/system_setup.sh"
    dest: "{{ tools_directory }}/system_setup.sh"
    owner: root
    mode: 0750
  when: run_from_iso|bool
