---

- name: Write out System_Setup
  copy:
    dest: "{{ tools_directory }}/system_setup.sh"
    content: "{{ hostvars[groups['installer-node'][0]]['cloudian_system_setup']['content'] | b64decode }}"
    owner: root
    mode: 0750
