---

- name: Disable IPv6 all
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    reload: yes

- name: Disable IPv6 default
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    reload: yes
