---

- name: Copy RPM packages
  copy:
    src: "{{ item }}"
    dest: "/tmp"
  with_fileglob:
    - "packages/centos/7/*.rpm"
  when: ( ansible_distribution_major_version == "7")

# optionally add packages here
- name: Install gdisk
  yum:
    name: /tmp/gdisk-0.8.6-5.el7.x86_64.rpm
    state: present
