---

- name: Configuring Networking
  # TODO: fail if physical interfaces do not exist
  template:
    src: ifcfg.j2
    # as dots have been replaced by _'s, revert that
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item[0] | regex_replace('_', '.') }}"

  loop: "{{ interfaces.items() }}"
  tags:
    - networking
