---

- name: Configuring Networking
  # TODO: fail if physical interfaces do not exist
  template:
    src: ifcfg.j2
    # as dots have been replaced by _'s, revert that
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item[0] | regex_replace('_', '.') }}"
  loop: "{{ interfaces.items() }}"

- name: Configure Static Routes
  template:
    src: route.j2
    # as dots have been replaced by _'s, revert that
    dest: "/etc/sysconfig/network-scripts/route-{{ item[0] | regex_replace('_', '.') }}"
  loop: "{{ interfaces.items() }}"
  when: item[1]['static-routes'] is defined
